// Project: to build a rock paper scissors game //

// User selects 1 of 3 options, rock, paper and scissors and stores the result in a variable. The computer generates a random selection of the same 3 options and stores it in another variable. If the user and computer pick the same option, print "Tie game." Remaining matchups below: //

// If user picks rock and computer picks scissors, print "You win" //
// If user picks rock and computer picks paper, print "You lose" //
// If user picks paper and computer picks rock, print "You win" //
// If user picks paper and computer picks scissors, print "You lose" //
// If user picks scissors and computer picks paper, print "You win" //
// If user picks scissors and computer picks rock, print "You win" //